language: node_js
services:
    - mysql
dist: bionic
before_script:
    - cp .env.travis .env
    - mysql -e 'CREATE DATABASE test_grapher;'
script:
    - yarn testcheck
cache: yarn
notifications:
    email:
        on_success: never
        on_failure: always
